#!/usr/bin/env bash

set -uxe

bin_parent=$1
# parent folder path of the target bin dir
zipped_file=bin.zip
# s3 public url
rm -rf /tmp/$zipped_file
curl https://myapp-public.s3.amazonaws.com/$zipped_file -o /tmp/$zipped_file
unzip -ou /tmp/$zipped_file -d $bin_parent
